const jokes = [
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why was the math book sad? Because it had too many problems.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I used to play piano by ear, but now I use my hands.",
  "Why don't oysters donate to charity? Because they're shellfish.",
  "Why don't skeletons play church music? Because they have no organs.",
  "I told my wife she was overreacting. She said, 'That's a lie; I never overreact!'",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "I told my computer I needed a break. Now it won't stop sending me vacation ads.",
  "I told my therapist about my addiction to breakdancing. He told me to pop, lock, and drop it.",
  "Why don't scientists trust stairs? Because they're always up to something.",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "Why did the belt go to jail? For holding up a pair of pants!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the coffee file a police report? It got mugged.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "Why did the coffee file a police report? It got mugged.",
  "Why don't oysters donate to charity? Because they're shellfish.",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "I told my wife she was overreacting. She said, 'That's a lie; I never overreact!'",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "I told my computer I needed a break. Now it won't stop sending me vacation ads.",
  "Why don't skeletons play church music? Because they have no organs.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I told my therapist about my addiction to breakdancing. He told me to pop, lock, and drop it.",
  "Why don't scientists trust stairs? Because they're always up to something.",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "Why did the belt go to jail? For holding up a pair of pants!",
  "Why did the math book look sad? Because it had too many problems.",
  "I used to play piano by ear, but now I use my hands.",
  "Why don't oysters donate to charity? Because they're shellfish.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "I told my wife she was overreacting. She said, 'That's a lie; I never overreact!'",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the coffee file a police report? It got mugged.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "I told my computer I needed a break. Now it won't stop sending me vacation ads.",
  "Why don't skeletons play church music? Because they have no organs."
];

const newJokes = () =>{
  let randomNumber = Math.floor(Math.random() * jokes.length)

  document.getElementById("jokes-display").innerHTML = jokes[randomNumber];
}
